AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'Gemfile.lock'
    - 'vendor/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'