source 'https://rubygems.org'
gem 'actionpack', '~> 7.0.8'    # Required for routing and controllers
gem 'actionview', '~> 7.0.8'    # Required for Rails API rendering
gem 'activesupport', '~> 7.0.8'
gem 'httparty', '~> 0.21.0'
gem 'puma', '~> 5.6'
gem 'rails', '~> 7.0.8'
gem 'railties', '~> 7.0.8'
group :development, :test do
  gem 'rspec-rails', '~> 5.1'
  gem 'vcr', '~> 6.1'
  gem 'webmock', '~> 3.18'
end
group :development do
  gem 'rubocop', '~> 1.50', require: false
  gem 'rubocop-rails', '~> 2.18', require: false
end
