# .air.toml
root = "."
tmp_dir = "tmp"

[build]
    cmd = "go build -o ./tmp/main ./cmd/main.go"
    bin = "./tmp/main"
    log = "build.log"
    exclude = ["tmp/*" ,  "client/*"]
    include = ["**/*.go"]
    ignore = ["tmp/*" ]
    exclude_regex = ["_test.go"]
    pull = true

[color]
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"